export const SELECTED_PROJECTS = [
  {
    id: 1,
    date: "2024",
    category: "Company System",
    title: "RMS Avisha - Job Order System",
    image: "/images/rms-system/cover.jpg",
    isLive: true,
    logo: "/images/rms-system/icon.png",
    liveUrl: "https://www.rmsavisha.company/",
  },
  {
    id: 2,
    date: "2024",
    category: "Thesis Commission",
    title: "EduQuest - Online Quiz System",
    image: "/images/eduQuest/cover.jpg",
    isLive: true,
    logo: "/images/eduQuest/icon.png",
    liveUrl: "https://edu-quest-web-system.vercel.app/",
  },
  {
    id: 3,
    date: "2025",
    category: "Thesis Commission",
    title: "Veripay - HRIS - Payroll System (IoT)",
    image: "/images/veripay/cover.png",
    isLive: true,
    logo: "/images/veripay/icon.png",
    liveUrl: "https://veripay.pro",
  },
  {
    id: 4,
    date: "2025",
    category: "Educational System",
    title: "Gas Law Simulation",
    image: "/images/gas-sim/cover.jpg",
    isLive: true,
    logo: "/images/gas-sim/icon.svg",
    liveUrl: "https://gas-law-simulation-web.vercel.app/",
  },
];

export const PROJECTS = [
  {
    id: 1,
    date: "2024",
    category: "Thesis | Lab",
    title: "Autobox - Auto Annotation System",
    image: "",
    isLive: true,
    logo: "/images/others/autobox.gif",
    liveUrl: "https://autobox-sage.vercel.app/",
  },
  {
    id: 2,
    date: "2025",
    category: "Thesis Commission",
    title: "E-Habi - Walis Tambo",
    image: "",
    isLive: true,
    logo: "/images/others/e-habi.png",
    liveUrl: "https://e-habi.vercel.app/",
  },
  {
    id: 3,
    date: "2024",
    category: "Thesis Commission",
    title: "D3xtra - Dijkstra's Algo 3D Model",
    image: "/images/d3xtra/cover.jpg",
    isLive: false,
    logo: "/images/d3xtra/icon.png",
    liveUrl: null,
  },
  {
    id: 4,
    date: "2024",
    category: "Thesis Commission",
    title: "Sucat Barangay System",
    image: "",
    isLive: false,
    logo: "/images/sucat-system/icon.png",
    liveUrl: null,
  },
  {
    id: 5,
    date: "2024",
    category: "Company System",
    title: "RMS Avisha - Info Website",
    image: "",
    isLive: true,
    logo: "/images/rms-system/icon.png",
    liveUrl: "https://rms-avisha.vercel.app/",
  },
];
