export const SELECTED_PROJECTS = [
  {
    id: 1,
    date: "2024",
    category: "Company System",
    title: "RMS Avisha - Job Order System",
    image: "/images/rms-system/cover.jpg",
    isLive: true,
    logo: "/images/rms-system/icon.png",
  },
  {
    id: 2,
    date: "2024",
    category: "Thesis Commission",
    title: "EduQuest - Online Quiz System",
    image: "/images/eduQuest/cover.jpg",
    isLive: true,
    logo: "/images/eduQuest/icon.png",
  },
  {
    id: 3,
    date: "2024",
    category: "Thesis Commission",
    title: "D3xtra",
    image: "/images/d3xtra/cover.jpg",
    isLive: false,
    logo: null,
  },
  {
    id: 4,
    date: "2025",
    category: "Educational System",
    title: "Gas Law Simulation",
    image: "/images/gas-sim/cover.jpg",
    isLive: true,
    logo: "/images/gas-sim/icon.svg",
  },
];
