export const SELECTED_PROJECTS = [
  {
    id: 1,
    date: "2024",
    category: "Company System",
    title: "RMS Avisha - Job Order System",
    image: "/images/rms-system/cover.jpg",
    isLive: true,
    logo: "/images/rms-system/icon.png",
    liveUrl: "https://www.rmsavisha.company/",
  },
  {
    id: 2,
    date: "2024",
    category: "Thesis Commission",
    title: "EduQuest - Online Quiz System",
    image: "/images/eduQuest/cover.jpg",
    isLive: true,
    logo: "/images/eduQuest/icon.png",
    liveUrl: "https://edu-quest-web-system.vercel.app/",
  },
  {
    id: 3,
    date: "2025",
    category: "Thesis Commission",
    title: "Veripay - HRIS - Payroll System (IoT)",
    image: "/images/veripay/cover.png",
    isLive: true,
    logo: "/images/veripay/icon.png",
    liveUrl: "https://veripay.pro",
  },
  {
    id: 4,
    date: "2025",
    category: "Educational System",
    title: "Gas Law Simulation",
    image: "/images/gas-sim/cover.jpg",
    isLive: true,
    logo: "/images/gas-sim/icon.svg",
    liveUrl: "https://gas-law-simulation-web.vercel.app/",
  },
];
